/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.general;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;

/**
 *
 * @author lesly
 */
public class bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public bienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        elipsepeque2 = new javax.swing.JLabel();
        elipsepeque1 = new javax.swing.JLabel();
        polloPlatitos = new javax.swing.JLabel();
        elipseDerecha = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        texto2 = new javax.swing.JLabel();
        googleplay = new javax.swing.JLabel();
        appstore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(245, 245, 245));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        elipsepeque2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/elipse_peque2.png"))); // NOI18N
        background.add(elipsepeque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));

        elipsepeque1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/elipse_peque1.png"))); // NOI18N
        background.add(elipsepeque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        polloPlatitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/pollon.png"))); // NOI18N
        background.add(polloPlatitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        elipseDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/elipse_grande.png"))); // NOI18N
        background.add(elipseDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/wikilogo1.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/texto.png"))); // NOI18N
        background.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/btnLog1.png"))); // NOI18N
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/btnLog2.png"))); // NOI18N
        btnLogin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/btnLog2.png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        background.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/btnSignUp.png"))); // NOI18N
        btnSignUp.setBorderPainted(false);
        btnSignUp.setContentAreaFilled(false);
        btnSignUp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/btnSignUp2.png"))); // NOI18N
        btnSignUp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/btnSignUp2.png"))); // NOI18N
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        background.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        texto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/texto2.png"))); // NOI18N
        background.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        googleplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/googlePlay.png"))); // NOI18N
        background.add(googleplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        appstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_general/appstore.png"))); // NOI18N
        background.add(appstore, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        iniciar_sesion is = new iniciar_sesion();
        is.setVisible(true);
        //Cerrar la Bienvenida
        setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        registro r = new registro();
        r.setVisible(true);
        //Cerrar la Bienvenida
        setVisible(false);
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            //UIManager.setLookAndFeel(new FlatLightLaf());
            FlatArcOrangeIJTheme.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appstore;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel elipseDerecha;
    private javax.swing.JLabel elipsepeque1;
    private javax.swing.JLabel elipsepeque2;
    private javax.swing.JLabel googleplay;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel polloPlatitos;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables
}
