/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.admin;

import java.time.LocalDate;

/**
 *
 * @author lesly
 */
public class admin_dash extends javax.swing.JPanel {

    /**
     * Creates new form admin_dash
     */
    public admin_dash() {
        initComponents();
        //Para mostrar la fecha actual
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", " ;septiembre",
             "octubre", "noviembre", "diciembre"};
        lblFecha.setText("Hoy es " + dia + " de " + meses[month - 1]+ " de " + year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFecha = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFecha.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(170, 89, 19));
        lblFecha.setText("Fecha de hoy");
        lblFecha.setBorder(new javax.swing.border.MatteBorder(null));
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFecha;
    // End of variables declaration//GEN-END:variables
}
